# ComplyEdge — EU AI Act Article 16: Provider Obligations
#
# Legal citation: Regulation (EU) 2024/1689, Article 16
# Effective: 2025-02-02 (prohibited) / 2026-08-02 (high-risk & GPAI)
# Condition type: deterministic
# Enforcement layer: layer1
# Status: approved
# Approved by: Leo Celis on 2026-07-09 (agent authoring)

package complyedge.highrisk.art16_provider_obligations

import rego.v1

default violation := false

violation if {
	input.jurisdiction == "EU"
	pattern_match
}

pattern_match if {
	patterns := [
		"(?:place|placing|sell|deploy|launch|release)\\w*\\s+high[\\-\\s]?risk\\s+ai\\s+(?:on\\s+(?:the\\s+)?eu\\s+market|in\\s+(?:the\\s+)?union)\\s+(?:without|lacking)\\s+(?:ce\\s+marking|conformity\\s+assessment|registration)",
		"high[\\-\\s]?risk\\s+ai\\s+(?:without|no)\\s+(?:ce\\s+marking|conformity\\s+assessment|eu\\s+declaration)",
	]

	text := lower(input.text)
	some pattern in patterns
	regex.match(pattern, text)
}

rule_id := "rego-art16-001"

citation := "Regulation (EU) 2024/1689, Article 16 (Obligations of providers of high-risk AI systems): Providers of high-risk AI systems shall: (a) ensure that their high-risk AI systems are compliant with the requirements set out in Section 2; (b) indicate on the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, as applicable, their name, registered trade name or registered trade mark, the address at which they can be contacted; (c) have a quality management system in place which complies with Article 17; (d) keep the documentation referred to in Article 18; (e) when under their control, keep the logs automatically generated by their high-risk AI systems as referred to in Article 19; (f) ensure that the high-risk AI system undergoes the relevant conformity assessment procedure as referred to in Article 43, prior to its being placed on the market or put into service; (g) draw up an EU declaration of conformity in accordance with Article 47; (h) affix the CE marking to the high-risk AI system or, where that is not possible, on its packaging or its accompanying documentation, to indicate conformity with this Regulation, in accordance with Article 48; (i) comply with the registration obligations referred to in Article 49(1); (j) take the necessary corrective actions and provide information as required in Article 20; (k) upon a reasoned request of a national competent authority, demonstrate the conformity of the high-risk AI system with the requirements set out in Section 2; (l) ensure that the high-risk AI system complies with accessibility requirements in accordance with Directives (EU) 2016/2102 and (EU) 2019/882."
severity := "high"

remediation := "Complete conformity assessment, CE marking, and EU registration before market placement."

result := {
	"violation": violation,
	"rule_id": rule_id,
	"citation": citation,
	"severity": severity,
	"remediation": remediation,
}
